### ISSUE TITLE
Update gradle script, SDK target version and automate build with GitHub actions

### ISSUE THREAD

**Issue by flavio20002** [flavio20002/CatholicBible#2]

**Comment by flavio20002** [comment]
@MrRar Can you help me with that? Thanks a lot!

**Comment by MrRar** [comment]
> @MrRar Can you help me with that? Thanks a lot!

It's not like I whipped this up in 3 hours. I've actually been working on it all week.

I'm not really an Android developer but recently I got interested in Android development. I also want to learn Flutter.

**Comment by flavio20002** [comment]
@MrRar 370 (2023.5.1) is available for internal test and your mail should be there. I rebased all the commits.

**Comment by MrRar** [comment]
What do you mean exactly? I signed up for the beta program on Google Play and I'm not seeing anything other than the old version.

What do you mean by "your mail should be there"?
